version: "3.3"

services:
  dev-server:
    container_name: car-prod-server
    build:
      tags:
        - "car-prod-server:latest"
      context: .
      dockerfile: Dockerfile
      target: production
    env_file: ./.env.prod
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    env_file: .env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  static_value:
  media_value:
